export const scripts = Object.fromEntries(
  Object.entries({
    Indic: ["Pallawa", "Sanskrit", "Grantha"],
    "Mon-Burmese": [
      "Old Mon",
      "Mon",
      "Myanmar",
      "S'gaw Karen",
      "Kayah Li",
      "Shan",
      "Khamti",
      "Tai Le",
    ],
    Khmer: ["Khmer"],
    Cham: ["Cham Srak", "Cham Thrah"],
    Sukhothai: [
      "Sukhothai",
      "Thai Lanna",
      "Thai",
      "Thai Noi",
      "Lao Buhan",
      "Lao",
      "Tai Viet",
      "Lai Thai",
    ],
    Sinitic: ["Chu Nom", "Hokkien"],
    Batak: ["Angkola", "Toba", "Pakpak", "Mandailing", "Karo", "Simalungun"],
    Kawi: ["Kawi", "Buda"],
    Hanacaraka: ["Jawa", "Sunda", "Bali", "Sasak", "Cacarakan", "Madura"],
    Lontaraq: ["Lontara", "Makassar", "Mbojo"],
    Ulu: ["Rejang", "Lampung", "Incung"],
    Baybayin: [
      "Baybayin",
      "Hanunó'o",
      "Buhid",
      "Tagbanwa",
      "Palaw'an",
      "Kulitan",
      "Ibalnan",
    ],
    Arabic: ["Pegon", "Jawi", "Batang Arab", "Sorabe"],
  }).map(([key, value]) => [key, value.slice().sort()]),
);
